### ISSUE TITLE
Offene Fragen

### ISSUE THREAD

**Issue by eoss-sh** [smartive-education/app-thierry-und-simon#23]
## Fragen zum Projekt und Umsetzung
- Im Profil kann man "meine Likes" anwählen - woher bekommt man diese Infos?
- Wenn man ein anderes Profil besucht, steht, ob man dem User folgt. Diese Info scheint die API auch nicht herzugeben.
- Section empfohlene User und empfohlene Mumbles - woher kommen die? (Profilpage neuer User) 
- Was macht das Settings Zahnrad?
- Meine Mumbles kann ich über die API nicht abfragen, wie baut man die Profile Page auf?
-

**Comment by THRY** [comment]
Im Profil kann man "meine Likes" anwählen - woher bekommt man diese Infos?
--> über /posts/search mit argument likedby

**Comment by THRY** [comment]
Wenn man ein anderes Profil besucht, steht, ob man dem User folgt. Diese Info scheint die API auch nicht herzugeben.
--> ja, das gibt es nicht, kann man weglassen

**Comment by THRY** [comment]
Meine Mumbles kann ich über die API nicht abfragen, wie baut man die Profile Page auf?
--> über get /posts argument creator mitgeben

**Comment by THRY** [comment]
Hashtags müssen nicht umgesetzt werden, gibt aber Bonuspunkte

**Comment by THRY** [comment]
Wordspinner für Loginseite:
https://github.com/smartive-education/design-system-component-library-z-index/blob/main/src/Components/WordSpinnerAnimation/WordSpinnerAnimation.tsx

**Comment by THRY** [comment]
Frage von mir: Wie machen wir Änderungen in Storybook und wie kommen diese Änderungen wieder in die App?

**Comment by eoss-sh** [comment]
> Frage von mir: Wie machen wir Änderungen in Storybook und wie kommen diese Änderungen wieder in die App?
> 
> * z.B. Änderungen bei Buttons (OnClick event) oder bei Modal (open/close state)

@THRY ich habe das mal getestet, man kann im alten Projekt einfach eine neue Version machen und diese dann im App-Projekt installieren. Im GH4 Branch habe ich das mal gemacht und die neue NaviButton Komponente aus dem Design System genutzt. 

Um zu updaten habe ich im `package.json` die Version manuell aktualisiert und einfach neu `npm install` gemacht. Da gibt es wohl elegantere Methoden?

**Comment by eoss-sh** [comment]
> Anwendung von State Machines oder usedispatch hook?

`useDispatch` wäre Redux / Redux Toolkit, oder? Ich würde mal als andere Alternative noch `useContext` vorschlagen. Ev. reicht das? Ich denke aber die Erwartung wäre schon was anderes zu nehmen.

**Comment by eoss-sh** [comment]
# Neue Fragen
Gibt es bei Replies auch wieder replies? Im Figma schon, in der API aber nicht, oder? @THRY

**Comment by THRY** [comment]
Hoi @eoss-sh nein, soweit ich das verstanden habe nur die direkten replys auf ein mumble
